### ISSUE TITLE
Revisão da tradução do README

### ISSUE THREAD

**Issue by rgaiacs** [paternogbc/studyGroup#3]
1. Trocar
   
   > Se algumas de nossas instruções não funcionar ou não fizer sentido, abra um issue or email sciencelab@mozillafoundation.org.
   
   por
   
   > Se algumas de nossas instruções não funcionam ou não fazem sentido, abra um issue ou envie um email sciencelab@mozillafoundation.org.
2. Precisa remover "Check out the Handbook".
3. Após "confira o Manual do Grupo de Estudo Mozilla!" mencionar que o manual encontra-se em inglês.
4. Trocar
   
   > Como criar o seu próprio Website Grupo de Estudo Mozilla?
   
   por 
   
   > Como criar o site do seu próprio Grupo de Estudo Mozilla?
5. Trocar
   
   > ós podemos te ajudar.
   
   por
   
   > ós podemos lhe ajudar.

**Comment by paternogbc** [comment]
Valeu! ;)

**Comment by paternogbc** [comment]
Muito obrigado pelas contribuições, foram excelentes. você quer que eu faça as modificações ou você quer fazer um pull request?

**Comment by rgaiacs** [comment]
>  Muito obrigado pelas contribuições, foram excelentes. você quer que eu faça as modificações ou você quer fazer um pull request? 

Pode fazer as modificações.

**Comment by paternogbc** [comment]
beleza!

Vou fazer e dou um commit. 
Depois disso, praticamente terminamos. Ai é só esperar as recomendações do Bill. 

Vou fazer as modificações amanha.

Um grande abs,
Guga
